### ISSUE TITLE
Add ESIP badges to the readme

### ISSUE THREAD

**Issue by roomthily** [ESIPFed/cor#32]
As I lack auth for a PR.

This will add a Testbed badge and a Semantic Web badge:

`<a href="http://esipfed.org">![](http://badge.esipfed.org/testbed.svg?display=logo)</a> <a href="http://esipfed.org">![](http://badge.esipfed.org/semanticweb.svg?display=logo)</a>`

**Comment by graybeal** [comment]
Also added to the Wiki. Thanks!!
