### ISSUE TITLE
Upload new version of SWEET to COR

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/cor#34]
Hi @carueda  it would be great if we could remove any previous versions of SWEET from the COR and for us to reference the development version of SWEET such that it is always up-to-date.
Can you deal with this?
Thank you in advance Carlos

**Comment by carueda** [comment]
Hi @lewismc 
All previously SWEET entries have just been removed from the COR instance.

Will next look into registering the new artifacts. This will start with the master file https://raw.githubusercontent.com/ESIPFed/sweet/master/sweetAll.ttl and then recursively with all its imported ontologies. For all of this I'm using my ad-hoc [orr-reg](https://github.com/mmisw/orr-reg) tool. For the registration, will implement a straightforward location "resolution" strategy based on a simple replacement from `http://sweetontology.net/_NAME_` to `https://raw.githubusercontent.com/ESIPFed/sweet/master/_NAME_.ttl`.

**Comment by graybeal** [comment]
Well, I'm a little late to this party, but for future reference: The principled model for managing versions is that once a version is created, it stays available for future users to access, even if it must be deprecated. COR is a bit of a special case, and this may have just been an interim 'non-public' version, and we don't support deprecated ontologies in the ORR anyway, so almost surely not a crisis that the existing version(s) got removed. I just want to be sure we don't get in the habit of deleting existing semantic resources at will—comparing them to more recent semantic resources can be very important.

**Comment by carueda** [comment]
The new 222 SWEET ontologies have just been registered: http://cor.esipfed.org/ont/#/so/sweetontology

Closing this.  

At some point I'll see how to enable automatic harvesting.

**Comment by carueda** [comment]
Ah, and I just re-enabled notifications (didn't of course want all of you to get the 222 emails).

**Comment by carueda** [comment]
Hi @lewismc 
Just redid the registration because I forgot to associate an organization (I picked "esip" this time) and visibility (set to "public").   I'm not sure about the intended status so I left it undefined.  Just let me know if you need a specific status to be associated (draft, unstable, testing, stable, ...).
