### ISSUE TITLE
update COR wiki on GitHub

### ISSUE THREAD

**Issue by graybeal** [ESIPFed/cor#36]
Update the wiki content to reflect the current status of COR in ESIP.

**Comment by carueda** [comment]
Don't want to edit the wikis directly (at least for now) but instead make some comments here.

Re this part in https://github.com/ESIPFed/cor/wiki/Deployment-Approach :

> ## In the repositories
> 
> An ESIP [mmiorr repository](http://github.com/esipfed/mmiorr) has been created and maintained as a fork of the MMI ORR software. This ESIP mmiorr repository will be used as the basis of ESIP's Community Ontology Repository service. Thus ESIP will always have control over this software, although for the most part it is expected to mirror MMI's software.

1. note, `mmiorr` is the **old** version 2. Also, the whole system is now comprised of two main components, the backend and the frontend.
1.  Ideally, **no** forking for purposes of having a **separate** line of development, but only for purposes of regular development in the spirit of fork-and-pull-requests against upstream repo. Of course, the separate line of development is always an open option!

> 
> When modifications are made to the ESIPFed/mmiorr repository, the ORR team will at its discretion merge modifications that are appropriate for the MMI ORR, back to the mmisw/mmiorr repository. These merges upstream should not have any impact on the ESIP software, and should not prevent the ESIPFed/mmiorr repository from continuing to track improvements to MMI's ORR, as desired.

**Comment by graybeal** [comment]
On the home page we have this:

- Background and Motivation — Why are we doing this?
-- updated this today, is now acceptably current
- Deployment Approach — What's going on technically?
-- this has a bunch of technical material that is not consistent in style or content with the other pages, and I'm not sure all of it should be publicly visible. Can anyone help?
- Management Process — How will this work be managed?
-- I deleted the part of this that was very old, and put To Be Provided instead
- Operational Overview — How will the COR work?
-- updated to be current
- Documentation and Contacts — Find out more!
- Original COR Proposal
