### ISSUE TITLE
Add cron job to relaunch instance.

### ISSUE THREAD

**Issue by ESIPlab** [ESIPFed/cor#39]
Carlos and Annie will touch bases on this.

**Comment by abburgess** [comment]
@carueda time to touch bases on this next week?

**Comment by carueda** [comment]
@abburgess apologies for the delay to respond..

As a quick "solution" I just set the following cronjob under cor-admin1:

```
@reboot sleep 60s && docker start mongo agraph orr
```

It's not the most elegant or efficient but it has proved useful in the past.

`systemd` would be possible better approach, could you help doing some research about using it to start docker containers  (note: I assume the docker engine itself is already being started at boot time)?

**Comment by abburgess** [comment]
Sure, I can do some reading!

**Comment by carueda** [comment]
Just taking note of a relevant reference: https://docs.docker.com/compose/compose-file/#restart (it looks like docker-compose already provides settings to indicate automatic restart)

**Comment by carueda** [comment]
Thanks @lewismc  for closing.

To be clear, this was actually resolved a while ago: No need for cronjob;  and `restart: always` was added for the various services in docker-compose.
