### ISSUE TITLE
omv and omvm vocabularies should be registered in the repo

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#41]
Why aren't dc and dct namespace used where appropriate?  At least an omv/omvm to dc, dct, dcat mapping?

**Comment by graybeal** [comment]
agree the vocabularies should be registered.

the reason dc/dct were not used is that when the metadata vocabulary was created, DC did not have unique identifiers and DCT didn't exist (best of my recollection). We used OMV as the only existing standard that covered a broad range of critical metadata, and added OMVMMI terms for things that were missing. At the time we thought we established the standard, but relatively few chose to follow us. (A few did though!)  

Also it was not a common practice until pretty recently to cut-and-paste terms from 5 or 6 vocabularies to serve your needs. Being as I'm not fond of that practice, I might prefer the linking approach you suggest.

A new ontology metadata standard has had a lot of work done on it (MOD) and it will probably be the best place to go next.

**Comment by smrgeoinfo** [comment]
is this the MODS you are thinking of? https://www.loc.gov/standards/mods/modsrdf/primer.html

There is a more recent paper suggesting updates to OMV by Min Et al (https://www.researchgate.net/publication/305400728_Towards_a_Standard_Ontology_Metadata_Model), but I don't see any indication of an implementation of the recommended updates.

**Comment by graybeal** [comment]
Yes, sorry, left out a lot of backstory. The actual ongoing work has been led by Clement Jonquet, paper is Biswanath Dutta, Anne Toulet, Vincent Emonet & Clement Jonquet. New Generation Metadata vocabulary for Ontology Description and Publication, In 11th Metadata and Semantics Research Conference, MTSR'17. Tallinn, Estonia, November 2017, link to PDF is http://www.lirmm.fr/~jonquet/publications/documents/Article_MTSR-2017_MOD1.2.pdf. 

Clement's team, Anne in particular, did a pretty thorough analysis of existing metadata initiatives, and came up with the content recommended in the paper. The paper by MIn et al was referencing this work.

**Comment by smrgeoinfo** [comment]
The github repo is at https://github.com/sifrproject/MOD-Ontology, but there are no tags or releases, and I'm hesitant to link to something in a working branch.   I posted a question about stable releases in their github https://github.com/sifrproject/MOD-Ontology/issues/17.  Doesn't look like its time to retool CORs to use MOD yet.

**Comment by biswanathdutta** [comment]
@smrgeoinfo For publications on MOD, besides the MTSR'17 paper, you may also look at the first publication at DC'15 here http://dcpapers.dublincore.org/pubs/article/view/3758

**Comment by smrgeoinfo** [comment]
I"m closing this one, thanks for the pointers to MOD, and perhaps at some point we'll modify COR to use MOD instead of OMV, but for now we're using OMV and will pursue getting the version we're using registered in COR so there's some way to dereference the URIs for the vocabulary.
