### ISSUE TITLE
DC metadata not recognized when linking to ontology via URL

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#42]
I'm registering SKOS vocabularies from the IUGS CGI; they all have dc metadata in the conceptScheme elements with dct title, date, creator, and description, and skos editorialNote and changeNote (e.g. http://resource.geosciml.org/vocabulary/cgi/2016/contacttype.rdf) , but these don't show up with the ontology metadata when I do the upload. Seems like at least the dc and dct elements should be recognized.

**Comment by graybeal** [comment]
By 'recognized' you mean that we should be monitoring all incoming ontologies for those metadata fields and using them in our metadata header?  That's a good idea, but not a small task—there are 5 or 6 standards in use for metadata for semantic content at this point. 

And we'll have to keep track of the original terms so if someone changes the metadata the metadata would be written back out to the correct (original) attribute. I guess these remote-hosted ontologies should only be read-only ontologies, not capable of being modified.

**Comment by smrgeoinfo** [comment]
I'm loading ontologies that have included metadata in SKOS, DC and DCT elements, and was hoping that the content from those would show up in upload process so I don't have to re-enter it all. I guess this would require having mappings from OMV and OMVM to other newer vocabularies, and then using those mappings to populate metadata when an existing ontology is registered.

**Comment by graybeal** [comment]
A workaround that required less software update, hence perhaps faster (but of course with less reward) might be to write a script to populate the metadata fields and submit it via API. (I am not sure whether metadata can be updated independently of ontology; API may say or @carueda may know.)

**Comment by smrgeoinfo** [comment]
Seems like a deep problem that will require vocabulary mapping and code updates, not likely to happen soon. We'll just have to be satisfied with cutting/pasting/typing in the registration forms.
