### ISSUE TITLE
need better display for SKOS vocabulary

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#43]
Since SKOS properties do not appear in the  NamedIndividual descriptions in the LODE display; the properties of individuals should show up in the HTML representation.  e.g. http://www.essepuntato.it/lode/owlapi/http://cor.esipfed.org/ont/api/v0/ont%3Firi=http://resource.geosciml.org/classifierscheme/cgi/2016.01/eventenvironment#d4e2185

**Comment by lewismc** [comment]
Resolving this issue.
