### ISSUE TITLE
URI for omv and omvm vocabularies resolves to advertising site

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#44]
goes to http://ibooked.no/onotoware.html, a Norwegian site about resorts in Greece.  Bogus intro text says "The OntoWare Group provides organizational and legal support for a broad range of Semantic Web related software projects. "    Looks like something has been hacked?

**Comment by graybeal** [comment]
Or potentially the OMV folks don't serve their ontology any more, which would be worse.

**Comment by smrgeoinfo** [comment]
The ontoware site got shut down in 2009: https://web.archive.org/web/20091101012322/http://ontoware.org:80/shutdown.html
The files still exist in subversion:
https://sourceforge.net/projects/omv2.  Files haven't been touched since 2010. 
I'm copying their subversion content into the  cors repo here, and will load the ontologies in the registry.

**Comment by smrgeoinfo** [comment]
The link to the owl file in sourceforge is an html download page--there doesn't seem to be a URL that will get the actual file that we could link to in CORS.   I think we should load OMV 2.4.1 from our copy here in the CORS repo.  Pull request coming.

**Comment by carueda** [comment]
@smrgeoinfo ,  Trying to understand the issue here (also looking at your PR)... Unless the overall idea is to change the OMV original URIs to something under our control (which I doubt), I'd say this is out of our scope.   The fact that those URIs resolve to something out there different to what they used to is something we can not (and should not, IMO) take control.

Your PR says, "Copy to repo here for registration in COR." But why not simply download those locally and then proceed with their registration?

Thoughts?

**Comment by smrgeoinfo** [comment]
I'm not sure where locally would be in the 'download locally'. What I was thinking is that we'd copy the files to our repo, so we know they're preserved, and then load the current version (or whichever we're using) into COR.  If I understand correctly, you're thinking that loading into COR is sufficient as a mechanism to preserve the ontology?  Seems like that would work.  Would we want to load all the versions and ancillary files that are in the OMVfiles repo branch from #46 PR?
  
I certainly don't think we want to redefine all the URIs, rather, we need a way to resolve them to some useful representation on the web, which currently can't be done (unless I'm missing something)? 
Getting the ontology in COR will provide a way to dereference the OMV concepts at least in the COR context., using the pattern http://cor.esipfed.org/ont?iri=http://omv.ontoware.org/2005/05/ontology#FormalityLevel  .

It would of course be nice if omv.ontoware.org/2005/05/ontology would redirect to the COR (or some other) resolution service, but like you said, that's not under our control.
