### ISSUE TITLE
add uptime monitoring/notification

### ISSUE THREAD

**Issue by graybeal** [ESIPFed/cor#47]
Add a monitoring service (either StatusCake or Uptime Robot could work—I know about StatusCake a little) to keep track of when COR goes down, and sends email (and ideally text message) to interested parties. (List to be determined, but likely Annie and one or more of John, Carlos, and Lewis.) 

NewRelic is another option but I think is too heavyweight.

The ideal solution would also generate an uptime report, though I predict it will very rarely add any value. But having that can help prove my claim that it 'never goes down'.

**Comment by abburgess** [comment]
@graybeal @carueda I have a notification if the instance goes down in Cloudwatch. You should both be getting an email to confirm. Is this sufficient?
