### ISSUE TITLE
SKOS rdf/xml upload error

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#49]
using a remote URL:
http://resource.geosciml.org/vocabulary/cgi/2016/geneticcategory.rdf
http://resource.geosciml.org/vocabulary/cgi/2016/featureobservationmethod.rdf
http://resource.geosciml.org/vocabulary/cgi/2016/lineationtype.rdf

Get error message
"Cannot recognize ontology format
The given URL does not resolve to a recognized ontology format.", and can't continue with upload. All of these vocab files are generated by the same automated process, I'm stumped figuring out why these don't work.

They load fine from the URL using Protege 5.0.0

**Comment by graybeal** [comment]
I note that both of them have a 'gremlin' character (per BBEdit's Zap Gremlins option). 

In geneticcategory you have a smart quote in "Earth's", in featureobservationmethod it's an ellipsis after "ruler…", and in lineationtype it's an ellipsis in "whole…that". Not sure but I think that's incompatible with the header 'encoding="UTF-8"' string.

**Comment by smrgeoinfo** [comment]
That's probably the problem, thanks John. I'll see if we can fix those gremlin characters in the source ontology.

**Comment by carueda** [comment]
I just tried the upload step with geneticcategory.rdf while inspecting the backend log.

It looks like this:

```
loading model ...

trying rdf...
ERROR org.apache.jena.riot - [line: 1, col: 1 ] Content is not allowed in prolog.

trying ttl 
ERROR org.apache.jena.riot - [line: 1, col: 1 ] Out of place: [KEYWORD:ï]

trying n3
ERROR org.apache.jena.riot - [line: 1, col: 1 ] Out of place: [KEYWORD:ï]

trying nt
ERROR org.apache.jena.riot - [line: 1, col: 2 ] Failed to find a prefix name or keyword: »(187;0x00BB)

trying rj
ERROR org.apache.jena.riot - [line: 1, col: 1 ] Expected a { character to start a JSON Object but got [KEYWORD:ï]

trying jsonld
org.apache.jena.riot - [line: 1, col: 2 ] Unrecognized token 'ï': was expecting ('true', 'false' or 'null')

trying owx
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
The following parsers were tried:
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) OWLOBOParser
6) KRSS2OWLParser
7) ManchesterOWLSyntaxOntologyParser 
...
Encountered 'ï»¿<?xml version="1.0" encoding="UTF-8"?>' at line 1 column 1. ...
```

In conclusion, it seems the file contents starts with the byte order mark (BOM) , see https://en.wikipedia.org/wiki/Byte_order_mark , in particular, note:

> BOM use is optional. Its presence interferes with the use of UTF-8 by software that does not expect non-ASCII bytes at the start of a file but that could otherwise handle the text stream.

One other pointer I just found by googling for `'ï»¿'` : https://stackoverflow.com/questions/3255993/how-do-i-remove-%C3%AF-from-the-beginning-of-a-file.

So , @smrgeoinfo can you confirm this is actually the case with your files? BTW, the other characters mentioned by John should be OK (as long as the file is in UTF-8).

**Comment by smrgeoinfo** [comment]
Thanks Carlos, I'll look into it

**Comment by smrgeoinfo** [comment]
I saved locally, using Notepad++ to change encoding to 'Encode in UTF-8'  (was 'Encode in UTF-8-BOM).
LineationType and GeneticCategory loaded fine from local copy on my computer. 
featureobservationmethod.rdf loaded ok, but when I tried to update the metadata got the { "error": "No graph writer for 'OWX'"}  problem
