### ISSUE TITLE
Keyword search throws error

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#50]
try http://cor.esipfed.org/ont#/kw/lithology
After about 1 minute, returns:
```
[2018-07-24T15:06:26-07:00] An error occurred with request: GET http://cor.esipfed.org/sparql
Response from server:
 data: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/sparql\">GET&nbsp;/sparql</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n</body></html>\n"
 status: 502
```

seems like it should get some hits, e.g. 
http://cor.esipfed.org/ont?iri=http://resource.geosciml.org/classifierscheme/cgi/2016.01/metamorphicgrade

**Comment by carueda** [comment]
(Stephen, thanks very much for all the testing and feedback!)

I just tried http://cor.esipfed.org/ont#/kw/lithology and it responded right away.

Seems like this one had the same cause as #52 , which I addressed yesterday by re-starting AllegroGraph, the service that powers the triplestore/SPARQL endpoint. @graybeal captured  mmisw/orr-ont#65 and mmisw/orr-ont#66 as part of the issue so hopefully those will help make the system more stable in a future version.  Thanks again!
