### ISSUE TITLE
Concept IRI doesn't resolve

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/cor#51]
http://cor.esipfed.org/ont?iri=http://resource.geosciml.org/classifier/cgi/descriptionpurpose/defining_norm returns an error:
```
{
  "msg": "resolveUri: error getting term",
  "error": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/ont/api/v0/ont\">GET&nbsp;/ont/api/v0/ont</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n</body></html>\n"
}
```

but 
http://resource.geosciml.org/classifier/cgi/descriptionpurpose/defining_norm but defining_norm is a named individual in http://cor.esipfed.org/ont?iri=http://resource.geosciml.org/classifierscheme/cgi/2016.01/descriptionpurpose.  Shouldn't it show up as a search result?

**Comment by carueda** [comment]
http://cor.esipfed.org/ont?iri=http://resource.geosciml.org/classifier/cgi/descriptionpurpose/defining_norm returns OK so closing this one. Also see #50 , #52
