### ISSUE TITLE
COR ont service is down

### ISSUE THREAD

**Issue by graybeal** [ESIPFed/cor#52]
The ont service is not responsive:

```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /ont.
Reason: Error reading from remote server
```

The page at cor.esipfed.org is responsive, and the AWS instance is up.

**Comment by graybeal** [comment]
I've contacted Annie (Carlos is out) and we'll look at this in the morning.

**Comment by carueda** [comment]
Seems like it was Allegrograph the container that started misbehaving, that is, not responding to some request from the ORR container. 

I just restarted Allegrograph and all seems back up.

To make sure the triple store is up to date, I also jsut ran the "reload triple store" function using the Admin UI at http://cor.esipfed.org/ont#/ts

Sorry, not much time now or tomorrow to do a more thorough investigation ... but two quick ideas to keep in mind:

- upgrade allegrograph (as already suggested elsewhere)
- include some timeout in requests from ORR to more gracefully handle the case where allegrograph stops responding.

-carlos

**Comment by graybeal** [comment]
Created https://github.com/mmisw/orr-ont/issues/65 and https://github.com/mmisw/orr-ont/issues/66 to capture those ideas.
