### ISSUE TITLE
Set proper address/server for email notifications

### ISSUE THREAD

**Issue by carueda** [ESIPFed/cor#53]
@abburgess @lewismc @graybeal 

Just noted that recent registrations into the COR were not successfully being notified to the list of email addresses indicated in `~cor-admin1/COR/config/notifyemails`.   I just took care of this, see below for details.

But this serves as a reminder that a more proper ESIP controlled email address and server should be used for the relevant configuration section (and not the address/server that is also being used in other ORR instances).

The relevant section to be change in `~cor-admin1/COR/config/orront.conf` is:
```
## ---------------------------------------------------------------------------
## (Required) Settings for the ORR to be able to send out emails (when user
## resets password; notifications about registrations, etc.)
email {
  ## (required) account used for sending emails.
  ## This account information must be valid in the server indicated below.
  account {
    username = "someaddr@esipcor.example.org"
    password = "*****"
  }

  ## (required) corresponding email server for the account above.
  server {
    host = "smtp.example.org"
    port = 465
    prot = "smtps"
    debug = false
  }

  ...
}
```

----
gmail issue: Looking at the log (`docker logs -f --tail=100 orr`) it was immediately clear this was because Google/Gmail has been preventing emails from the configured `email.account.username` address, which is a gmail account, because they are originating from a new machine (the new Amazon instance--so this is one other piece arising from the recent migration). I have followed the usual procedure when this has happened in the past so gmail should now allow emails from that machine.

**Comment by lewismc** [comment]
@carueda it sounds like this is a configuration issue which needs to be addressed by an admin during deployment or upgrade. Correct? If so, we need to augment the configuration and deployment documentation.

**Comment by carueda** [comment]
It's currently documented in the deployment template: https://github.com/mmisw/orr-instance-template/blob/master/config/orront.conf

**Comment by carueda** [comment]
I'm not seeing any changes related with this.

**Comment by graybeal** [comment]
Lewis suggests getting in touch with Dan Keyes, who deals with mailing lists. If that fails we can try someone else.

**Comment by lewismc** [comment]
I'm working with Megan and Annie on this

**Comment by lewismc** [comment]
@carueda @graybeal Megan and Patty have created the email. I have the details. Where should we keep them?

**Comment by carueda** [comment]
hi @lewismc , as noted in the description:

> The relevant section to be changed in `~cor-admin1/COR/config/orront.conf` is:
> ```
> ## ---------------------------------------------------------------------------
> ## (Required) Settings for the ORR to be able to send out emails (when user
> ## resets password; notifications about registrations, etc.)
> email {
>   ## (required) account used for sending emails.
>   ## This account information must be valid in the server indicated below.
>   account {
>     username = "someaddr@esipcor.example.org"
>     password = "*****"
>   }
> 
>   ## (required) corresponding email server for the account above.
>   server {
>     host = "smtp.example.org"
>     port = 465
>     prot = "smtps"
>     debug = false
>   }
> 
>   ...
> }
> ```
> 

Then, for this to take effect you can do:

```
cd ~/COR
source setenv.sh
docker-compose stop orr
docker-compose rm orr
docker-compose start orr
docker logs --tail=10 -f orr
```

**Comment by carueda** [comment]
Hi @lewismc ,

Just capturing here my attempts to enable the new account details that you provided.

Your post on slack with the new account details:

> The following email setup has been completed
> email - cor-admin@esipfed.org
> Temporary password -   ....
> imap.gmail.com
> Port 993
> Protocol - STMP
> They will just need to open gmail and put in the email address and password.  No other configuration should be necessary.  Gmail will ask them to change the password upon first login. 

Btw, "STMP" seems like a typo, so I entered "SMTP".

However, while testing with an ontology registration, I got in the backend log:

```
javax.mail.MessagingException: Could not connect to SMTP host: imap.gmail.com, port: 993, response: -1
```

So, since this seems to still be via "gmail", I reverted the server settings to 
```
    host = "smtp.gmail.com"
    port = 465
    prot = "smtps"
```

Then did a new version registration ... but got:

```
javax.mail.AuthenticationFailedException: 535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 194sm22462977pfu.165 - gsmtp
```

Now, just trying again with port 993, but I got:

```
javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 993, response: -1
```

So, no luck.  I'm reverting to the previous account.

**Comment by lewismc** [comment]
Thanks for trying this out @carueda I'll work with the relevant ESIP folks to double check the information., You are totally right, `STMP` protocol does not even exist! I'll double check everything.

**Comment by carueda** [comment]
@lewismc Also, it is possible that the credentials per se are OK but that gmail is not allowing the request because it's coming from a new "device" (that is, the COR machine). This has happened in the past with other ORR instances and the solution has been to go to the gmail page where the owner of the account can confirm that those attempted requests are legitimate.

**Comment by lewismc** [comment]
This is exactly what has happened @carueda I logged into the Google gmail console and can see the **critical security alert**. 
I went ahead and resolved that issue (see response in Slack). 
Could you please try again?
Thank you

**Comment by carueda** [comment]
Thanks @lewismc .

Done.  As you may have already noticed, based on an ontology submission, the associate email notification (to some of us admins) are now coming from the new account.

**Comment by lewismc** [comment]
Yeah I saw it come in. Thank you @carueda excellent.
