### ISSUE TITLE
Updating GCMD Science Keywords in the COR  /  Server Maintenance/tuning

### ISSUE THREAD

**Issue by carueda** [ESIPFed/cor#56]
("moved" from https://github.com/ESIPFed/sweet/issues/80 --reported by @tbs1979)

I am trying to update the GCMD Science Keyword Version in the http://cor.esipfed.org and when I try to save the file, I get the following error '"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/ont/api/v0/ont\">PUT&nbsp;/ont/api/v0/ont</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n</body></html>\n"'. I am also trying the update the URL to https://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords/

![image](https://user-images.githubusercontent.com/25930554/35517621-0086856e-04dd-11e8-9853-285ae65ccbe7.png)

----
I go to http://cor.esipfed.org/ont?iri=http://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords > Edit New Version > Edit Metadata > Original Source tab > Edit Version '8.6' > Register > Proceed with registration

**Comment by carueda** [comment]
Starting from http://cor.esipfed.org/ont?iri=http://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords  I was just able to reproduce this again.

```
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request 
... PUT /ont/api/v0/ont

Reason: Error reading from remote server
```

However, no errors in the ORR backend log. Perhaps an apache proxy misconfiguration here(?)

**Comment by carueda** [comment]
But in the local apache access log I do see the following while retrying:

```
sudo tail -f /var/log/httpd/access_log

... - - [07/Sep/2018:01:20:00 +0000] 
"PUT /ont/api/v0/ont HTTP/1.1" 502 407 
"http://cor.esipfed.org/ont?iri=http://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"

... - - [07/Sep/2018:01:43:59 +0000] 
"PUT /ont/api/v0/ont HTTP/1.1" 502 407 
"http://cor.esipfed.org/ont?iri=http://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
```

**Comment by carueda** [comment]
So, the reported [407](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407) error is actually triggered by a timeout while the ORR is processing the update.

In one more attempt while still trying to figure this out, the ORR was actually able complete the update, despite apache having given up and reported the proxy error.

So, in summary:  ( @tbs1979 FYI )

- The intended 8.6 version is now reflected at the COR.

- Part of the approach to address these timeouts is to improve performance on the ORR server itself. And I just entered https://github.com/mmisw/orr-ont/issues/67 for that purpose.

- However, perhaps there's also some local degradation on the COR amazon instance, will look into as a most immediate step.


![image](https://user-images.githubusercontent.com/556505/45195175-36e28780-b20b-11e8-8791-9c5b3cb29802.png)


.... Hmm, however, note that just a subsequent GET request involved when navigating to display the ontology is also triggering a proxy error (most likely, also a timeout):

![image](https://user-images.githubusercontent.com/556505/45195536-ee2bce00-b20c-11e8-844f-2106c6ff4bfa.png)

**Comment by carueda** [comment]
A [ctop](https://github.com/bcicen/ctop) report on the COR machine seems to show normal resource consumption.

![image](https://user-images.githubusercontent.com/556505/45195631-6a261600-b20d-11e8-9d24-0d62197319f7.png)

Perhaps this amazon instance could also use some increased CPU power(?) (@abburgess , @lewismc ).

**Comment by lewismc** [comment]
@carueda I take it that the orchestration defines the default memory allocation for the ORR container at 4GB? Same with MongoDB? or did you do this manually?

But yes, MEM looks to be fine/

**Comment by carueda** [comment]
Hmm, well, I just noted that other operations were also timing out, for example, just while trying to log in.

so, decided to just restart all containers:

```
cd COR
source setenv.sh
docker-compose restart
```

(Then reload triple store --using Admin option on the UI)

Now, the system seems back to normal and "quick" operations.  I was able to login quickly, and a resolution for http://cor.esipfed.org/ont?iri=http://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords was acceptably fast (given the large size of the ontology).

**Comment by lewismc** [comment]
No joke, I was just running an ontology alignment and I noticed that COR was down for about a minute or so... HAHA.
This sounds great @carueda thank you for investigating. It is not abnormal for us to need to restart docker-compose up every now and then. I think that is acceptable???

**Comment by carueda** [comment]
@lewismc (just noted your comment above ... well  the two ones above  ;;))

Only Allegrograph has an explicit `mem_limit: 1g` setting in ORR's docker-compose.yml.

But yes, definitely a good point!   we need to decide on good memory settings for the ORR and Mongo containers as well, also looking into the actual memory available on this amazon instance.

Yeah, perhaps we can set a cronjob to restart everything every week (say, saturday "midnight") as an interim measure...

**Comment by smrgeoinfo** [comment]
perhaps the title for this issue should be updated to reflect that its more about server maintenance (If I understand the discussion correctly)?

**Comment by lewismc** [comment]
@smrgeoinfo thats a fair comment... it now is yes you are correct.

**Comment by carueda** [comment]
@smrgeoinfo that for the comment -- I just applied the ops and performance labels, and edited the title a bit.

**Comment by carueda** [comment]
Just revisited this and decided to close it as fixed (all seems working ok).

A lot of water has gone under the bridge (e.g., , we have done one (or two?) more migrations to new Amazon instances, AGraph now has `shm_size: 3g`, the ORR is now 3.9.3 (3.7.0 when this was reported, etc.)
