### ISSUE TITLE
Implement backup sequence

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/cor#57]
It is essential that any data stored in the system is backed up.
@carueda are there any other data sources we need to back up other than Mongo and AGraph?

**Comment by carueda** [comment]
`/home/cor-admin1/COR/ is the critical location (in particular the subdirs `orr_data/` and `mongo_data/` there).  AGraph data is not critical at all as the triple store can be repopulated at any time from the actual registered ontologies (there's an admin operation for that in the UI).

**Comment by lewismc** [comment]
@abburgess OK can you please check that ```/home/cor-admin1/COR/``` is backed-up? If it is, then please post the location of the backup here and we can close this issue. Thank you

**Comment by abburgess** [comment]
<img width="1641" alt="screen shot 2019-01-25 at 11 15 51 am" src="https://user-images.githubusercontent.com/7329728/51767580-aeb62f00-2092-11e9-8b1a-165ad64c86c6.png">

The backup is of the EBS volume holding the EC2 COR instance on AWS. That will include COR.

**Comment by lewismc** [comment]
Thanks folks,
