### ISSUE TITLE
403 error on Protege load of COR hosted ontology

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/cor#58]
I attempted to load the ADO ontology that is in COR (http://cor.esipfed.org/ont/~rduerr/ADO) in my desktop version of Protege (version 5.5.0 Build beta-8) and received the following error:

`Server returned HTTP response code: 403 for URL: http://cor.esipfed.org/ont/~rduerr/ADO` 

which indicates that protege didn't have permission to access that link even though I made the ontology public?  What's up with that?

**Comment by graybeal** [comment]
The problem *might* be that this URL uses content negotiation, and Protege isn't correctly specifying what it wants (e.g., that it wants XML/RDF).  But that surprises me. (I can find out for sure later today, if need be.)

I note that the download location for the XML/RDF ontology is given as "http://cor.esipfed.org/ont/api/v0/ont?format=rdf&iri=http://cor.esipfed.org/ont/~rduerr/DataLicenses", so you could try opening that in Protege..

**Comment by graybeal** [comment]
Sorry, example used wrong ontology. Replace 'DataLicenses' with 'ADO' in above link...

**Comment by rduerr** [comment]
Done but still getting a 403 on either the ttl or rdf versions...

`Server returned HTTP response code: 403 for URL: http://cor.esipfed.org/ont/api/v0/ont?format=ttl&iri=http://cor.esipfed.org/ont/~rduerr/ADO`

**Comment by carueda** [comment]
Looks like this is the known Protégé issue (along with the strict request interception by Cloudflare) diagnosed in the SWEET tracker: https://github.com/ESIPFed/sweet/issues/150#issuecomment-514337050

**Comment by rduerr** [comment]
This is now fixed...
