### ISSUE TITLE
Issues updating ontology metadata in COR

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/cor#59]
After it was pointed out to me that I had a typo in the dc:title of the "Academic Disciplines Ontology" I tried to fix that issue by using the COR Edit new version -> Edit metadata facility.  However, none of my metadata showed up, so could not be edited.  In particular there was no dc:title field in the list of available fields.  

Attempts to update it using the omv:name field on the form failed to update the dc:title field which remained unchanged.

**Comment by graybeal** [comment]
Thanks Ruth for pinning this down.

It reminds me that an issue we thought about when writing COR was how much of the internal ontology metadata we wanted to 'take charge of'.  I'm not sure if it's a good idea for us to assume the name the user enters in COR metadata should overwrite a dc:title within the ontology (and similarly for other external properties). Thoughts?

**Comment by rduerr** [comment]
I think that if there is a term in the ontology that is a well-known term (like dc:title), that's what COR should display in its corresponding field.  Why make people enter data twice.  This also has the advantage of forcing agreement on standard ways of annotating ontologies!  It forces and implicit "same as" on terms between two sets of annotations!  Badly needed!!!

**Comment by lewismc** [comment]
This has been captured at https://esipfed.github.io/stc/UseCases/STCUseCasesAndRequirements.html#UpdateMetadata

**Comment by carueda** [comment]
@rduerr 

> However, none of my metadata showed up, so could not be edited. In particular there was no dc:title field in the list of available fields.

I note that all metadata properties in this ontology are associated to the subject `http://cor.esipfed.org/ont/~rduerr/ADO/` (note the trailing slash), not with `http://cor.esipfed.org/ont/~rduerr/ADO`, which is the actual ontology IRI:

![image](https://user-images.githubusercontent.com/556505/66174244-fec59800-e608-11e9-9015-88e9d21de66b.png)

That's why you don't see any values in the metadata section.

**Comment by carueda** [comment]
@rduerr  In case it helps, attached is your latest turtle version but with a fix where line 786 reads:

```
<http://cor.esipfed.org/ont/~rduerr/ADO>   a   owl:Ontology ;
```
instead of

```
:   a   owl:Ontology ;
```

[ADO.ttl.txt](https://github.com/ESIPFed/cor/files/3688650/ADO.ttl.txt)

**Comment by rduerr** [comment]
Thanks!  This problem is fixed!  On to the next one....
