### ISSUE TITLE
Need to add EarthCube as an organization in COR

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/cor#62]
I've been instructed to set up earthcube as an organization in COR.  The regular create account doesn't do it.  Apparently only administrators can set up organizations.  

Per the documentation:

- Short name: earthcube
- full name: EarthCube Office (ESO)
- URL: https://www.earthcube.org/
- Members: rduerr and a bunch of people I don't know the esip account names for (Ilya Zazlovski, Steve Richards, etc.)

**Comment by carueda** [comment]
@rduerr Thanks for the info.  I just created this org. I added you and Stephen Richard (`smresipcor`) as members (seems like Ilya doesn't have an account on COR), but this can be edited anytime.

![image](https://user-images.githubusercontent.com/556505/66084012-7a98e500-e522-11e9-8502-7ce4ef59dd34.png)

**Comment by rduerr** [comment]
Thanks so much!
