### ISSUE TITLE
prefix.cc URIs do not resolve properly

### ISSUE THREAD

**Issue by brandonnodnarb** [ESIPFed/cor#72]
All SWEET ttl files were mapped to consistent NS prefixes via prefix.cc (see https://github.com/ESIPFed/sweet/blob/master/sweetPrefixes.ttl for full list).

For example the NS for matrMaterial.ttl file is somamin, available at http://prefix.cc/somamin.  However, when accessing the page, clicking the ontology URI redirects to an "IRI not found" page on COR.  I note that removing the trailing slash OR replacing it with a hash (#) allows the URI to resolve to the PyLODE page --- I assume because conneg is working.  

Questions:
1) Is this related to #37 ?
2) Is this on the COR side or CloudFlare or...?  
3) Do all the URIs need to be re-mapped?

related to https://github.com/ESIPFed/sweet/issues/232

**Comment by carueda** [comment]
> However, when accessing the page, clicking the ontology URI redirects to an "IRI not found" page on COR.

This behavior is expected: The link shown at prefix.cc indicates the associated **namespace**, not an IRI that corresponds to an actual ontology.  When you remove the trailing slash, you are then getting a proper ontology IRI.  When you replace it with a hash, that hash becomes "invisible"  to COR so it still will resolve to the ontology IRI.

**Comment by brandonnodnarb** [comment]
Thanks, @carueda.  Interesting -- it's not what *I* would expect.  :)   However, that seems to be quite a separate issue -- given the title of this one anyway.  I'll close this and maybe inquire further at the next COR meeting.

**Comment by carueda** [comment]
@brandonnodnarb ... probably consider something like the following,  but only for an HTML response (not for any of the semantic serializations) :

With the `somamin ` -> `http://sweetontology.net/matrMineral/` example:

- along with the current "IRI not found" error,  have the COR also suggest something like, "Did you mean `http://sweetontology.net/matrMineral`?"

or:

- Have the COR automatically retry the request without the trailing slash.

Again, the current behavior is, strictly speaking, correct.  The above idea is more for UX purposes.

**Comment by graybeal** [comment]
I concur with all, and think that having COR automatically retry the request without the trailing slash is the right move—saves a lot of pain and unlikely to cause other issues. (And that retry must be supported by ontology repos all over the place, or we users who are navigating to ontologies would get a pile of "not found" messages all the time, wouldn't we?)

On reflection, it seems an odd hiccup in prefix.cc approach, I wonder if *they* see this all the time?

**Comment by brandonnodnarb** [comment]
Agreed.  For reference, DublinCore may be inline with your second point above @carueda, e.g.
> Have the COR automatically retry the request without the trailing slash.

as http://prefix.cc/dc --> http://purl.org/dc/elements/1.1/ (top link) which re-directs to https://www.dublincore.org/specifications/dublin-core/dcmi-terms/
whereas, ssn provides a straight download:
http://prefix.cc/ssn --> http://www.w3.org/ns/ssn/ (which goes no where for me but pops up the download dialogue)

Either approach seems reasonable to me.

**Comment by carueda** [comment]
Thanks for the replies.  Just captured at https://github.com/mmisw/orr-portal/issues/178

**Comment by carueda** [comment]
@brandonnodnarb @graybeal @lewismc 

OK, I have just implemented this in ORR [3.9.81](https://mmisw.org/orrdoc/changes/),

... which I just enabled for the COR.

First, make sure the new version is refreshed in your browser (just reload, for example, the main page: http://cor.esipfed.org/ont and see the new version at the top of the page as usual).

Then try visiting http://cor.esipfed.org/ont?iri=http://sweetontology.net/matrMineral/

**Comment by brandonnodnarb** [comment]
Cool.  Yeah, that works.  Many thanks, @carueda
