### ISSUE TITLE
IRI not found // AllegroGraph connection refused

### ISSUE THREAD

**Issue by brandonnodnarb** [ESIPFed/cor#75]
receiving an error message in the header of COR pages:

```
{
  "msg": "resolveUri: error getting term",
  "error": {
    "error": "error querying iri=http://sweetontology.net/relaSpace/above: java.net.ConnectException: Connection refused: agraph/172.24.0.2:10035 to http://agraph:10035/repositories/mmiorr"
  }
}
```
This happens on any page.  For example, from here  http://cor.esipfed.org/ont?iri=http://sweetontology.net/relaSpace
select any of the IRIs on the page, again for example, http://cor.esipfed.org/ont?iri=http://sweetontology.net/relaSpace/across

Is AllegroGraph down?

**Comment by carueda** [comment]
Not much to add here, but just to tag @graybeal in case he can restart the service.

**Comment by carueda** [comment]
I fixed this by just restarting the AllegroGraph container.
